### ISSUE TITLE
Advise

### ISSUE THREAD

**Issue by gangtie95** [HITSZ-HLT/KA-Stance-Detection#2]
About the algorithm ‘save_csv’ which from tools.  One line of code is missing one parameter 'new_line='' ', if it weren't for this, there would be empty lines in the new generated file.

**Comment by Leon-Francis** [comment]
Really appreciate your kind advice. I think I have fixed this issue in commit a14c65b three months ago. Are you on the latest submitted version? If not, you can pull the latest version and try if it is fixed.

**Comment by Leon-Francis** [comment]
Since I didn't get your response for a couple of days, I will close this issue. If you have any further questions, feel free to open a new one.

**Comment by gangtie95** [comment]
Thank you very much for your reply. I'm sorry I didn't check my email in a timely manner. 
I have updated the latest version. 
Wishing you a smooth future in scientific research and publishing more papers!




| |
luffy
|
|
***@***.***
|
---- Replied Message ----
| From | Ang ***@***.***> |
| Date | 6/10/2024 16:06 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [HITSZ-HLT/KA-Stance-Detection] Advise (Issue #2) |

Closed #2 as completed.
